---
title: "FO - Hypothesis 1"
author: "Stefanie Meliss"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
options(scipen = 999)
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

# --- load libraries ---

devtools::source_url("https://github.com/stefaniemeliss/ambition_theme/blob/main/ambition_theme.R?raw=TRUE")

library(dplyr)
library(kableExtra)
require(ggpubr)
require(grid)


# --- define directories ---

cd = getwd()

dir_figs <- file.path(cd, "figures")
if (!dir.exists(dir_figs)) {
  dir.create(dir_figs)
}

dir_data <- file.path(cd, "data_safetycopy")
if (!dir.exists(dir_data)) {
  dir.create(dir_data)
}

dir = "C:/Users/stefanie.meliss/OneDrive - Ambition Institute/research_projects/2023_Q3_Decomp Recomp & FO Sims/Data/Final data files for analysis/FO"

copy_files <- F
if (copy_files) {
  files = list.files(path = dir, pattern = ".csv", full.names = T)
  file.copy(files, dir_data)
}

reproduce_analysis <- T
if (reproduce_analysis) {
  # use files previously stored
  dir <- dir_data
}

# --- read in data ---

df <- read.csv(file.path(dir,"All_data_FO.csv"))

# filter
df <- filter(df, Exclusion_sim_analysis  == 0)
```

### H1

```{r, results='asis', echo = F}
# --- H1 --- #

# sim 2 accuracy residualised #

# run regression
dv = "residuals_Sim2acc"
cov = "sim1_accuracy"
m1 <- lm(scale(get(dv)) ~ scale(get(cov)) + scale(FO),
         data = df)
# sjPlot::tab_model(m1, show.se = T, show.stat = T, show.ci = F)

# get beta coefs
tmp <- summary(m1)
coef <- as.data.frame(tmp$coefficients)
coef[, 4] <- ifelse(coef[, 4] < 0.001, "<.001", weights::rd(coef[, 4], 3))
coef[,-4] <- round(coef[, -4], 2)
coef$Predictors <- row.names(coef)
coef$Predictors <- ifelse(coef$Predictors == "scale(get(cov))", "Sim 1 measure",
                          ifelse(coef$Predictors == "scale(FO)", "FO",
                                 coef$Predictors))
coef$Estimate <- paste0(coef$Estimate, " (", coef$`Std. Error`, ")")
coef$`Std. Error` <- NULL
row.names(coef) <- NULL
coef$R2 <- ""
coef$R2[1] <- weights::rd(tmp$r.squared, 2)


coef_acc <- coef

# sim 2 tot residualised #

# run regression
dv = "residuals_Sim2tot"
cov = "sim1_ToT"
m1 <- lm(scale(get(dv)) ~ scale(get(cov)) + scale(FO),
         data = df)
# sjPlot::tab_model(m1, show.se = T, show.stat = T, show.ci = F)

# get beta coefs
tmp <- summary(m1)
coef <- as.data.frame(tmp$coefficients)
coef[, 4] <- ifelse(coef[, 4] < 0.001, "<.001", weights::rd(coef[, 4], 3))
coef[,-4] <- round(coef[, -4], 2)
coef$Predictors <- row.names(coef)
coef$Predictors <- ifelse(coef$Predictors == "scale(get(cov))", "Sim 1 measure",
                          ifelse(coef$Predictors == "scale(FO)", "FO",
                                 coef$Predictors))
coef$Estimate <- paste0(coef$Estimate, " (", coef$`Std. Error`, ")")
coef$`Std. Error` <- NULL
row.names(coef) <- NULL
coef$R2 <- ""
coef$R2[1] <- weights::rd(tmp$r.squared, 2)


coef_tot <- coef

# merge #
coef_h1 <- merge(coef_acc, coef_tot, by = "Predictors")
coef_h1$Predictors <- factor(coef_h1$Predictors, levels = coef_acc$Predictors)
coef_h1 <- coef_h1[order(coef_h1$Predictors), ]
idx_bold <- grep("FO", coef_h1$Predictors)

# add to markdown
kbl(coef_h1, row.names = F,
    col.names = gsub(".x|.y", "", names(coef_h1))) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  add_header_above(c(" " = 1, "Participant skill" = 4, "Time off task" = 4)) %>%
  row_spec(idx_bold, bold=T, hline_after = T)

```

```{r, echo = F}
px_w <- 2160
px_h <- 764

# group data into 25 equal-sized bins
tmp <- df %>% mutate(bin = ntile(FO, n = 25)) %>%
  # computed the mean of the x-variable and y-variable within each bin
  group_by(bin) %>% 
  summarise(fo = mean(FO),
            acc_change = mean(Diff_sim1A_Sim2A), 
            tot_change = mean(Diff_sim1ToT_sim2ToT)) 

# as facet # 
tmp_l <- reshape2::melt(tmp, id.vars = c("bin", "fo"))
# format 
tmp_l$variable <- ifelse(tmp_l$variable == "acc_change", "Participant skill", "Pupil time off task")
tmp_l$variable <- factor(tmp_l$variable, levels = c("Participant skill", "Pupil time off task"))

# skill
binned_skill <- ggplot(tmp_l[tmp_l$variable == "Participant skill", ], aes(x = fo, y = value)) + 
  geom_point(col = navy) +
  facet_grid(variable ~ .) +
  ylab("Improvement between simulator sessions 1 and 2") + 
  xlab("Feedback orientation") +
  coord_cartesian(ylim = c(0, 8), xlim = c(60, 100)) +
  ambition_theme 

# tot
binned_tot <- ggplot(tmp_l[tmp_l$variable == "Pupil time off task", ], aes(x = fo, y = value)) + 
  geom_point(col = navy) +
  facet_grid(variable ~ .) +
  ylab("Improvement between simulator sessions 1 and 2") + 
  xlab("Feedback orientation") +
  coord_cartesian(ylim = c(0, 60), xlim = c(60, 100)) +
  ambition_theme 

# do some arranging
binned <- ggarrange(binned_skill + rremove("ylab") + rremove("xlab"), # remove axis labels from plots
                    binned_tot + rremove("ylab") + rremove("xlab"), # remove axis labels from plots
                    nrow = 2, align = "v")

binned <- annotate_figure(binned, left = textGrob("Improvement between simulator sessions 1 and 2", 
                                        rot = 90, vjust = 1, gp = gpar(cex = 1)),
                bottom = textGrob("Feedback orientation", gp = gpar(cex = 1)))
binned
ggsave(plot = binned,
       filename = file.path(dir_figs, "FigureB1.jpg"), 
       units = "cm", width = 20, height = 15)

####

binned_skill <- ggplot(tmp_l[tmp_l$variable == "Participant skill", ], aes(x = fo, y = value)) + 
  geom_point(col = navy) +
  coord_cartesian(ylim = c(0, 8), xlim = c(60, 100)) +
  ambition_theme_minimal
ggsave(plot = binned_skill, 
       filename = file.path(dir_figs, "FigureB1_skill_minimal.jpg"), 
       units = "px", width = px_w, height = px_h, dpi = 300)


binned_tot <- ggplot(tmp_l[tmp_l$variable == "Pupil time off task", ], aes(x = fo, y = value)) + 
  geom_point(col = navy) +
  coord_cartesian(ylim = c(0, 60), xlim = c(60, 100)) +
  ambition_theme_minimal 
ggsave(plot = binned_tot, 
       filename = file.path(dir_figs, "FigureB1_tot_minimal.jpg"), 
       units = "px", width = px_w, height = px_h, dpi = 300)

```


### H1A

```{r, results='asis', echo = F}
# --- H1A --- #

# sim 2 accuracy residualised #

# run regression
dv = "residuals_Sim2acc"
cov = "sim1_accuracy"
# sim 2 accuracy residualised
m1 <- lm(scale(get(dv)) ~ 
           scale(get(cov)) +
           scale(FO) + 
           scale(working_memory) + 
           scale(conscientiousness) +
           scale(DAMMQ_sum) +
           scale(AGQ_mastery_approach) +
           scale(AGQ_mastery_avoidance) +
           scale(AGQ_perf_approach) +
           scale(AGQ_perf_avoidance),
         data = df
)
# sjPlot::tab_model(m1, show.se = T, show.stat = T, show.ci = F)

# get beta coefs
tmp <- summary(m1)
coef <- as.data.frame(tmp$coefficients)
coef[, 4] <- ifelse(coef[, 4] < 0.001, "<.001", weights::rd(coef[, 4], 3))
coef[,-4] <- round(coef[, -4], 2)
coef$Predictors <- c("(Intercept)", "Sim 1 measure", "FO", "Working memory", "Conscientiousness", "Task mastery",
                     "GO - mastery approach", "GO - mastery avoidance", "GO - performance approach", "GO - performance avoidance")
coef$Estimate <- paste0(coef$Estimate, " (", coef$`Std. Error`, ")")
coef$`Std. Error` <- NULL
row.names(coef) <- NULL
coef$R2 <- ""
coef$R2[1] <- weights::rd(tmp$r.squared, 2)


coef_acc <- coef

# sim 2 tot residualised #

# run regression
dv = "residuals_Sim2tot"
cov = "sim1_ToT"
m1 <- lm(scale(get(dv)) ~ 
           scale(get(cov)) +
           scale(FO) + 
           scale(working_memory) + 
           scale(conscientiousness) +
           scale(DAMMQ_sum) +
           scale(AGQ_mastery_approach) +
           scale(AGQ_mastery_avoidance) +
           scale(AGQ_perf_approach) +
           scale(AGQ_perf_avoidance),
         data = df
)
# sjPlot::tab_model(m1, show.se = T, show.stat = T, show.ci = F)

# get beta coefs
tmp <- summary(m1)
coef <- as.data.frame(tmp$coefficients)
coef[, 4] <- ifelse(coef[, 4] < 0.001, "<.001", weights::rd(coef[, 4], 3))
coef[,-4] <- round(coef[, -4], 2)
coef$Predictors <- c("(Intercept)", "Sim 1 measure", "FO", "Working memory", "Conscientiousness", "Task mastery",
                     "GO - mastery approach", "GO - mastery avoidance", "GO - performance approach", "GO - performance avoidance")
coef$Estimate <- paste0(coef$Estimate, " (", coef$`Std. Error`, ")")
coef$`Std. Error` <- NULL
row.names(coef) <- NULL
coef$R2 <- ""
coef$R2[1] <- weights::rd(tmp$r.squared, 2)


coef_tot <- coef

# merge #
coef_h1a <- merge(coef_acc, coef_tot, by = "Predictors")
coef_h1a$Predictors <- factor(coef_h1a$Predictors, levels = coef_acc$Predictors)
coef_h1a <- coef_h1a[order(coef_h1a$Predictors), ]
idx_bold <- grep("FO", coef_h1a$Predictors)

# add to markdown
kbl(coef_h1a, row.names = F,
    col.names = gsub(".x|.y", "", names(coef_h1a))) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  add_header_above(c(" " = 1, "Participant skill" = 4, "Time off task" = 4)) %>%
  row_spec(idx_bold, bold=T, hline_after = T)

```

### H1B

```{r, results='asis', echo = F, warning=F}
# --- H1B --- #

FOS <- c("FO_utility", "FO_accountability", "FO_awareness", "FO_efficacy")
FOS_out <- c("FO utility", "FO accountability", "FO social awareness", "FO self-efficacy")

# sim 2 accuracy residualised #

# run regression
dv = "residuals_Sim2acc"
cov = "sim1_accuracy"

for (i in 1:length(FOS)) {
  
  # run reg
  m1 <- lm(scale(get(dv)) ~ scale(get(cov)) + scale(get(FOS[i])),
           data = df)
  # sjPlot::tab_model(m1, show.se = T, show.stat = T, show.ci = F,pred.labels = c("Intercept", cov, FOS[i]))
  
  # get beta coefs
  tmp <- summary(m1)
  coef <- as.data.frame(tmp$coefficients)
  coef[, 4] <- ifelse(coef[, 4] < 0.001, "<.001", weights::rd(coef[, 4], 3))
  coef[,-4] <- round(coef[, -4], 2)
  coef$Predictors <- row.names(coef)
  coef$Predictors[3] <- FOS_out[i]
  row.names(coef) <- NULL
  coef$R2 <- ""
  coef$R2[1] <- weights::rd(tmp$r.squared, 2)
  
  
  if (i == 1) {
    coef_acc <- coef
  } else {
    coef_acc <- rbind(coef_acc, coef)
  }
  
}

# extract data for plot #
beta_acc <- coef_acc[grepl("FO", coef_acc$Predictors), c("Predictors", "Estimate", "Std. Error")]
beta_acc$DV <- "Participant skill"

# re-format columns
coef_acc$Estimate <- paste0(coef_acc$Estimate, " (", coef_acc$`Std. Error`, ")")
coef_acc$`Std. Error` <- NULL


# sim 2 tot residualised #

# run regression
dv = "residuals_Sim2tot"
cov = "sim1_ToT"
for (i in 1:length(FOS)) {
  
  # run reg
  m1 <- lm(scale(get(dv)) ~ scale(get(cov)) + scale(get(FOS[i])),
           data = df)
  # sjPlot::tab_model(m1, show.se = T, show.stat = T, show.ci = F, pred.labels = c("Intercept", cov, FOS[i]))
  
  # get beta coefs
  tmp <- summary(m1)
  coef <- as.data.frame(tmp$coefficients)
  coef[, 4] <- ifelse(coef[, 4] < 0.001, "<.001", weights::rd(coef[, 4], 3))
  coef[,-4] <- round(coef[, -4], 2)
  coef$Predictors <- row.names(coef)
  coef$Predictors[3] <- FOS_out[i]
  row.names(coef) <- NULL
  coef$R2 <- ""
  coef$R2[1] <- weights::rd(tmp$r.squared, 2)
  
  
  if (i == 1) {
    coef_tot <- coef
  } else {
    coef_tot <- rbind(coef_tot, coef)
  }
  
}

# extract data for plot #
beta_tot <- coef_tot[grepl("FO", coef_tot$Predictors), c("Predictors", "Estimate", "Std. Error")]
beta_tot$DV <- "Time off task"

# re-format columns
coef_tot$Estimate <- paste0(coef_tot$Estimate, " (", coef_tot$`Std. Error`, ")")
coef_tot$`Std. Error` <- NULL


# merge #
coef_h1b <- merge(coef_acc, coef_tot, by = 0)
coef_h1b$Row.names <- as.numeric(coef_h1b$Row.names)
coef_h1b <- coef_h1b[order(coef_h1b$Row.names),]
coef_h1b$Row.names <- NULL
coef_h1b$Predictors.y <- NULL
names(coef_h1b)[names(coef_h1b) == "Predictors.x"] <- "Predictors"
coef_h1b <- coef_h1b %>%
  select(Predictors, everything())
coef_h1b$Predictors <- ifelse(coef_h1b$Predictors == "scale(get(cov))", "Sim 1 measure", coef_h1b$Predictors)

idx_bold <- grep("FO", coef_h1b$Predictors)

# add to markdown
kbl(coef_h1b, row.names = F,
    col.names = gsub(".x|.y", "", names(coef_h1b))) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  add_header_above(c(" " = 1, "Participant skill" = 4, "Time off task" = 4)) %>%
  row_spec(idx_bold, bold=T, hline_after = T)



# create plot #
beta <- rbind(beta_acc, beta_tot)
beta$Predictors <- factor(beta$Predictors, levels = c("FO utility", "FO accountability", "FO social awareness", "FO self-efficacy"))
names(beta) <- c("FO subscale", "beta", "se", "DV")

px_w <- 2160
px_h <- 764
size_dot = 2

plt <- ggplot(data = beta, aes(x = `FO subscale`, y = beta)) +
  geom_hline(yintercept = 0, color = black, linetype = "dotted") +
  geom_errorbar(aes(ymin = beta-1.96*se, ymax = beta+1.96*se), width = .1) + 
  geom_point(size = size_dot, color = coral) +
  coord_cartesian(ylim = c(-.2, .4))+
  facet_grid(DV ~ .) +
  ylab("β") +
  ambition_theme
plt

ggsave(filename = file.path(dir_figs, "Figure3_H1B.jpg"), 
       units = "cm", width = 20, height = 12, dpi = 300)


plt <- ggplot(data = beta[beta$DV == "Participant skill", ], aes(x = `FO subscale`, y = beta)) +
  geom_hline(yintercept = 0, color = black, linetype = "dotted") +
  geom_errorbar(aes(ymin = beta-1.96*se, ymax = beta+1.96*se), width = .1) + 
  geom_point(size = size_dot, color = coral) +
  coord_cartesian(ylim = c(-.2, .4))+
  ylab("β") +
  ambition_theme_minimal
ggsave(plot = plt, 
       filename = file.path(dir_figs, "Figure3_H1B_skill_minimal.jpg"), 
       units = "px", width = px_w, height = px_h, dpi = 300)

plt <- ggplot(data = beta[beta$DV == "Time off task", ], aes(x = `FO subscale`, y = beta)) +
  geom_hline(yintercept = 0, color = black, linetype = "dotted") +
  geom_errorbar(aes(ymin = beta-1.96*se, ymax = beta+1.96*se), width = .1) + 
  geom_point(size = size_dot, color = coral) +
  coord_cartesian(ylim = c(-.2, .4))+
  ylab("β") +
  ambition_theme_minimal
ggsave(plot = plt, 
       filename = file.path(dir_figs, "Figure3_H1B_tot_minimal.jpg"), 
       units = "px", width = px_w, height = px_h, dpi = 300)


```

```{r, echo=F}
# --- create output for export ---#

# create headers
header <- coef_h1[1, ]
header[1, 2:ncol(header)] <- ""
header[, 1] <- "Hypothesis 1"

# rbind header with H1
coef_h1 <- rbind(header, coef_h1)

# create header
header[, 1] <- "Hypothesis 1A"

# rbind header with H1
coef_h1a <- rbind(header, coef_h1a)

# create header
header[, 1] <- "Hypothesis 1B"

# rbind header with H1
coef_h1b <- rbind(header, coef_h1b)

# final rbind
coefs <- rbind(coef_h1, coef_h1a, coef_h1b)

names(coefs) <- c("", "beta (SE)", "t", "p", "R2", "beta (SE)", "t", "p", "R2")
names(coefs) <- gsub(".1", "", names(coefs))

# save file
write.csv(coefs,
          file = file.path(cd, "H1.csv"),
          row.names = F)
```


