---
title: "FO - Hypothesis 2"
author: "Stefanie Meliss"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

# --- load functions from github ---

devtools::source_url("https://github.com/stefaniemeliss/ambition_theme/blob/main/ambition_theme.R?raw=TRUE")

library(tidyr)
library(dplyr)
library(kableExtra)

# --- read in data ---

cd = getwd()

dir = "C:/Users/stefanie.meliss/OneDrive - Ambition Institute/research_projects/Ark Feedback Orientation and Sims/Data/Final data files for analysis/FO"

setwd(dir)

df <- read.csv("All_data_FO.csv")

df <- filter(df, Exclusion_H2 == 0)

# script vars 

vars <- c("FO",
          "FO utility",
          "FO accountability",
          "FO social awareness",
          "FO self-efficacy")

# determine variable names: summed scores
vars_sum_1 <- c("FO",
            "FO_utility",
            "FO_accountability",
            "FO_awareness",
            "FO_efficacy")

vars_sum_2 <- c("FO.2",
            "FO_utility.2",
            "FO_accountability.2",
            "FO_awareness.2",
            "FO_efficacy.2")

# determine variable names: weighted scores
vars_wtd_1 <- c("FO_wtd",
            "FO_utility_wtd",
            "FO_account_wtd",
            "FO_aware_wtd",
            "FO_efficacy_wtd")

vars_wtd_2 <- c("FO2_wtd",
            "FO2_utility_wtd",
            "FO2_account_wtd",
            "FO2_aware_wtd",
            "FO2_efficacy_wtd")

```

### Pairwise t-tests one-sided

```{r, echo = F, results='asis'}

# create DF for export
out <- data.frame(
  variable = character(5),
  survey1 = character(5),
  survey2 = character(5),
  diff = character(5),
  ttest = character(5)
)

# determine variable names: summed scores
vars_1 <- vars_sum_1
vars_2 <- vars_sum_2

# loop over vraibles #

for (i in 1:length(vars)) {
  
  v1 <- vars_1[i]
  v2 <- vars_2[i]
  
  # run paired t-test
  ttest <- t.test(y = df[, v1],
                  x = df[, v2],
                  paired = T,
                  alternative = "greater")
  
  # get survey 1 descriptives
  survey1 <- round(psych::describe(df[, v1]), 2)
  # get survey 2 descriptives
  survey2 <- round(psych::describe(df[, v2]), 2)
  # get diff descriptives
  df$diff <- df[, v2] - df[, v1]
  diff <- round(psych::describe(df[, "diff"]), 2)
  hist(df$diff, main = paste0(vars[i]))
  
  # fill table #
  out[i, "variable"] <- vars[i]
  out[i, "survey1"] <- paste0(survey1$mean, " (", survey1$sd, ") [", survey1$min, "; ", survey1$max, "]")
  out[i, "survey2"] <- paste0(survey2$mean, " (", survey2$sd, ") [", survey2$min, "; ", survey2$max, "]")
  out[i, "diff"] <- paste0(diff$mean, " (", diff$sd, ") [", diff$min, "; ", diff$max, "]")
  out[i, "ttest"] <- paste0("t(", ttest$parameter, ") = ", round(ttest$statistic, 2), ", p = ", ifelse(ttest$p.value < 0.001, "<.001", weights::rd(ttest$p.value, 3)), ", Cohen's d = ", round(lsr::cohensD(y = df[, v1], x = df[, v2], method = "paired"), 2))
  
}

summed <- out

kbl(summed, caption = "Summed scores") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))


# create DF for export
out <- data.frame(
  variable = character(5),
  survey1 = character(5),
  survey2 = character(5),
  diff = character(5),
  ttest = character(5)
)

# determine variable names: weighted scores
vars_1 <- vars_wtd_1
vars_2 <- vars_wtd_2

# loop over vraibles #

for (i in 1:length(vars)) {
  
  v1 <- vars_1[i]
  v2 <- vars_2[i]
  
  # run paired t-test
  ttest <- t.test(y = df[, v1],
                  x = df[, v2],
                  paired = T,
                  alternative = "greater")
  
  # get survey 1 descriptives
  survey1 <- round(psych::describe(df[, v1]), 2)
  # get survey 2 descriptives
  survey2 <- round(psych::describe(df[, v2]), 2)
  # get diff descriptives
  df$diff <- df[, v2] - df[, v1]
  diff <- round(psych::describe(df[, "diff"]), 2)
  hist(df$diff, main = paste0(vars[i]))
  
  # fill table #
  out[i, "variable"] <- vars[i]
  out[i, "survey1"] <- paste0(survey1$mean, " (", survey1$sd, ") [", survey1$min, "; ", survey1$max, "]")
  out[i, "survey2"] <- paste0(survey2$mean, " (", survey2$sd, ") [", survey2$min, "; ", survey2$max, "]")
  out[i, "diff"] <- paste0(diff$mean, " (", diff$sd, ") [", diff$min, "; ", diff$max, "]")
  out[i, "ttest"] <- paste0("t(", ttest$parameter, ") = ", round(ttest$statistic, 2), ", p = ", ifelse(ttest$p.value < 0.001, "<.001", weights::rd(ttest$p.value, 3)), ", Cohen's d = ", round(lsr::cohensD(y = df[, v1], x = df[, v2], method = "paired"), 2))
  
}

weighted <- out

kbl(weighted, caption = "Weighted scores") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))


# combine both
out <- merge(summed, weighted, by = "variable")

write.csv(out, file = file.path(cd, "H2_onesided.csv"), row.names = F)

```




### Pairwise t-tests two-sided

```{r, echo = F, results='asis'}

# create DF for export
out <- data.frame(
  variable = character(5),
  survey1 = character(5),
  survey2 = character(5),
  diff = character(5),
  ttest = character(5)
)

vars <- c("FO",
          "FO utility",
          "FO accountability",
          "FO social awareness",
          "FO self-efficacy")

# determine variable names: summed scores
vars_1 <- vars_sum_1
vars_2 <- vars_sum_2

# loop over vraibles #

for (i in 1:length(vars)) {
  
  v1 <- vars_1[i]
  v2 <- vars_2[i]
  
  # run paired t-test
  ttest <- t.test(y = df[, v1],
                  x = df[, v2],
                  paired = T)
  
  # get survey 1 descriptives
  survey1 <- round(psych::describe(df[, v1]), 2)
  # get survey 2 descriptives
  survey2 <- round(psych::describe(df[, v2]), 2)
  # get diff descriptives
  df$diff <- df[, v2] - df[, v1]
  diff <- round(psych::describe(df[, "diff"]), 2)
  
  # fill table #
  out[i, "variable"] <- vars[i]
  out[i, "survey1"] <- paste0(survey1$mean, " (", survey1$sd, ") [", survey1$min, "; ", survey1$max, "]")
  out[i, "survey2"] <- paste0(survey2$mean, " (", survey2$sd, ") [", survey2$min, "; ", survey2$max, "]")
  out[i, "diff"] <- paste0(diff$mean, " (", diff$sd, ") [", diff$min, "; ", diff$max, "]")
  out[i, "ttest"] <- paste0("t(", ttest$parameter, ") = ", round(ttest$statistic, 2), ", p = ", ifelse(ttest$p.value < 0.001, "<.001", weights::rd(ttest$p.value, 3)), ", Cohen's d = ", round(lsr::cohensD(y = df[, v1], x = df[, v2], method = "paired"), 2))
  
}

summed <- out

kbl(summed, caption = "Summed scores") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))


# create DF for export
out <- data.frame(
  variable = character(5),
  survey1 = character(5),
  survey2 = character(5),
  diff = character(5),
  ttest = character(5)
)

# determine variable names: weighted scores
vars_1 <- vars_wtd_1
vars_2 <- vars_wtd_2

# loop over vraibles #

for (i in 1:length(vars)) {
  
  v1 <- vars_1[i]
  v2 <- vars_2[i]
  
  # run paired t-test
  ttest <- t.test(y = df[, v1],
                  x = df[, v2],
                  paired = T)
  
  # get survey 1 descriptives
  survey1 <- round(psych::describe(df[, v1]), 2)
  # get survey 2 descriptives
  survey2 <- round(psych::describe(df[, v2]), 2)
  # get diff descriptives
  df$diff <- df[, v2] - df[, v1]
  diff <- round(psych::describe(df[, "diff"]), 2)
  
  # fill table #
  out[i, "variable"] <- vars[i]
  out[i, "survey1"] <- paste0(survey1$mean, " (", survey1$sd, ") [", survey1$min, "; ", survey1$max, "]")
  out[i, "survey2"] <- paste0(survey2$mean, " (", survey2$sd, ") [", survey2$min, "; ", survey2$max, "]")
  out[i, "diff"] <- paste0(diff$mean, " (", diff$sd, ") [", diff$min, "; ", diff$max, "]")
  out[i, "ttest"] <- paste0("t(", ttest$parameter, ") = ", round(ttest$statistic, 2), ", p = ", ifelse(ttest$p.value < 0.001, "<.001", weights::rd(ttest$p.value, 3)), ", Cohen's d = ", round(lsr::cohensD(y = df[, v1], x = df[, v2], method = "paired"), 2))
  
}

weighted <- out

kbl(weighted, caption = "Weighted scores") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))


# combine both
out <- merge(summed, weighted, by = "variable")

write.csv(out, file = file.path(cd, "H2_twosided.csv"), row.names = F)

```

### Plots

```{r, echo = F, warning = F}

# --- prepare data ---

# filter and select: Feedback orientation
df_fo <- df %>%
  filter(Exclusion_H2==0) %>%
  select(participant, FO, FO.2) 
# reshape wide -> long
dfl_fo <- reshape2::melt(df_fo)
# format 
dfl_fo$variable <- ifelse(dfl_fo$variable == "FO", "1", "2")
dfl_fo$variable <- factor(dfl_fo$variable, levels = c("1", "2"))
dfl_fo$construct <- "Feedback orientation"
dfl_fo$comp <- "Summed score"

# filter and select: Feedback orientation weighted
df_fow <- df %>%
  filter(Exclusion_H2==0) %>%
  select(participant, FO_wtd, FO2_wtd) 
# reshape wide -> long
dfl_fow <- reshape2::melt(df_fow)
# format 
dfl_fow$variable <- ifelse(dfl_fow$variable == "FO_wtd", "1", "2")
dfl_fow$variable <- factor(dfl_fow$variable, levels = c("1", "2"))
dfl_fow$construct <- "Feedback orientation"
dfl_fow$comp <- "Weighted score"

# filter and select: Feedback efficacy
df_fo_e <- df %>%
  filter(Exclusion_H2==0) %>%
  select(participant, FO_efficacy, FO_efficacy.2) 
# reshape wide -> long
dfl_fo_e <- reshape2::melt(df_fo_e)
# format 
dfl_fo_e$variable <- ifelse(dfl_fo_e$variable == "FO_efficacy", "1", "2")
dfl_fo_e$variable <- factor(dfl_fo_e$variable, levels = c("1", "2"))
dfl_fo_e$construct <- "FO self-efficacy"
dfl_fo_e$comp <- "Summed score"

# filter and select: Feedback efficacy weighted
df_fo_ew <- df %>%
  filter(Exclusion_H2==0) %>%
  select(participant, FO_efficacy_wtd, FO2_efficacy_wtd) 
# reshape wide -> long
dfl_fo_ew <- reshape2::melt(df_fo_ew)
# format 
dfl_fo_ew$variable <- ifelse(dfl_fo_ew$variable == "FO_efficacy_wtd", "1", "2")
dfl_fo_ew$variable <- factor(dfl_fo_ew$variable, levels = c("1", "2"))
dfl_fo_ew$construct <- "FO self-efficacy"
dfl_fo_ew$comp <- "Weighted score"

# filter and select: Feedback utility 
df_fo_u <- df %>%
  filter(Exclusion_H2==0) %>%
  select(participant, FO_utility, FO_utility.2) 
# reshape wide -> long
dfl_fo_u <- reshape2::melt(df_fo_u)
# format 
dfl_fo_u$variable <- ifelse(dfl_fo_u$variable == "FO_utility", "1", "2")
dfl_fo_u$variable <- factor(dfl_fo_u$variable, levels = c("1", "2"))
dfl_fo_u$construct <- "FO utility"
dfl_fo_u$comp <- "Summed score"

# filter and select: Feedback utility weighted
df_fo_uw <- df %>%
  filter(Exclusion_H2==0) %>%
  select(participant, FO_utility_wtd, FO2_utility_wtd) 
# reshape wide -> long
dfl_fo_uw <- reshape2::melt(df_fo_uw)
# format 
dfl_fo_uw$variable <- ifelse(dfl_fo_uw$variable == "FO_utility_wtd", "1", "2")
dfl_fo_uw$variable <- factor(dfl_fo_uw$variable, levels = c("1", "2"))
dfl_fo_uw$construct <- "FO utility"
dfl_fo_uw$comp <- "Weighted score"

# filter and select: Feedback social awareness 
df_fo_s <- df %>%
  filter(Exclusion_H2==0) %>%
  select(participant, FO_awareness, FO_awareness.2) 
# reshape wide -> long
dfl_fo_s <- reshape2::melt(df_fo_s)
# format 
dfl_fo_s$variable <- ifelse(dfl_fo_s$variable == "FO_awareness", "1", "2")
dfl_fo_s$variable <- factor(dfl_fo_s$variable, levels = c("1", "2"))
dfl_fo_s$construct <- "FO social awareness"
dfl_fo_s$comp <- "Summed score"

# filter and select: Feedback social awareness weighted
df_fo_sw <- df %>%
  filter(Exclusion_H2==0) %>%
  select(participant, FO_aware_wtd, FO2_aware_wtd) 
# reshape wide -> long
dfl_fo_sw <- reshape2::melt(df_fo_sw)
# format 
dfl_fo_sw$variable <- ifelse(dfl_fo_sw$variable == "FO_aware_wtd", "1", "2")
dfl_fo_sw$variable <- factor(dfl_fo_sw$variable, levels = c("1", "2"))
dfl_fo_sw$construct <- "FO social awareness"
dfl_fo_sw$comp <- "Weighted score"

# filter and select: Feedback accountability 
df_fo_a <- df %>%
  filter(Exclusion_H2==0) %>%
  select(participant, FO_accountability, FO_accountability.2) 
# reshape wide -> long
dfl_fo_a <- reshape2::melt(df_fo_a)
# format 
dfl_fo_a$variable <- ifelse(dfl_fo_a$variable == "FO_accountability", "1", "2")
dfl_fo_a$variable <- factor(dfl_fo_a$variable, levels = c("1", "2"))
dfl_fo_a$construct <- "FO accountability"
dfl_fo_a$comp <- "Summed score"

# filter and select: Feedback accountability weighted
df_fo_aw <- df %>%
  filter(Exclusion_H2==0) %>%
  select(participant, FO_account_wtd, FO2_account_wtd) 
# reshape wide -> long
dfl_fo_aw <- reshape2::melt(df_fo_aw)
# format 
dfl_fo_aw$variable <- ifelse(dfl_fo_aw$variable == "FO_account_wtd", "1", "2")
dfl_fo_aw$variable <- factor(dfl_fo_aw$variable, levels = c("1", "2"))
dfl_fo_aw$construct <- "FO accountability"
dfl_fo_aw$comp <- "Weighted score"



## rbind all


# # --- create plot in facets: NOT USED ---
# 
# dfl <- rbind(dfl_fo, dfl_fow)
# dfl <- rbind(dfl, dfl_fo_e)
# dfl <- rbind(dfl, dfl_fo_ew)
# dfl$construct <- factor(dfl$construct, levels = c("FO", "FO self-efficacy"))
# 
# plt <- ggplot(data = dfl, aes(x = variable, y = value, group = 1)) +
#   stat_summary(fun = "mean", geom = "line") +
#   stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1) +
#   stat_summary(fun = "mean", geom = "point",size = size_dot, color = coral) +
#   ambition_theme + xlab("Survey") + ylab("Self-report measure") +
#   facet_grid(construct ~ comp, scales = "free_y")
# plt

# --- set some overall parameter --- #

size_dot = 2
ymin = 17
ymax = 29

# --- create facets for FO only ---

dfl <- rbind(dfl_fo, dfl_fow)
dfl$construct <- factor(dfl$construct, levels = c("FO", "FO self-efficacy"))

plt_fo <- ggplot(data = dfl, aes(x = variable, y = value, group = 1)) +
  stat_summary(fun = "mean", geom = "line") +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1) +
  stat_summary(fun = "mean", geom = "point",size = size_dot, color = coral) +
  ambition_theme + xlab("") + ylab("FO") +
  facet_grid(. ~ comp) + coord_cartesian(ylim = c(70, 90))
# plt_fo

plt_fo_spag <- ggplot(data = dfl, aes(x = variable, y = value, group = 1)) +
  geom_point(size = .5, color = black40) +
  geom_line(aes(group = participant), color = black40, linewidth = .5) +
  stat_summary(fun = "mean", geom = "line") +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1) +
  stat_summary(fun = "mean", geom = "point",size = size_dot, color = coral) +
  ambition_theme + xlab("") + ylab("FO") +
  facet_grid(. ~ comp) # + coord_cartesian(ylim = c(70, 90))
# plt_fo_spag

# --- create facets for FO efficacy only ---

dfl <- rbind(dfl_fo_e, dfl_fo_ew)
dfl$construct <- factor(dfl$construct, levels = c("FO", "FO self-efficacy"))

plt_fo_e <- ggplot(data = dfl, aes(x = variable, y = value, group = 1)) +
  stat_summary(fun = "mean", geom = "line") +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1) +
  stat_summary(fun = "mean", geom = "point",size = size_dot, color = coral) +
  ambition_theme + xlab("Survey") + ylab("FO self-efficacy") +
  facet_grid(. ~ comp) + coord_cartesian(ylim = c(ymin, ymax))
# plt_fo_e

plt_fo_e_spag <- ggplot(data = dfl, aes(x = variable, y = value, group = 1)) +
  geom_point(size = .5, color = black40) +
  geom_line(aes(group = participant), color = black40, linewidth = .5) +
  stat_summary(fun = "mean", geom = "line") +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1) +
  stat_summary(fun = "mean", geom = "point",size = size_dot, color = coral) +
  ambition_theme + xlab("Survey") + ylab("FO self-efficacy") +
  facet_grid(. ~ comp) #+ coord_cartesian(ylim = c(ymin, ymax))
# plt_fo_e_spag


## --- Combine to create Figure 2 ---

ggpubr::ggarrange(
  plt_fo, plt_fo_e, nrow = 2, align = "hv")
ggsave(filename = file.path(cd, "Figure2.jpg"), 
       units = "cm", width = 16, height = 12)


# --- create facets for FO accountability only ---

dfl <- rbind(dfl_fo_a, dfl_fo_aw)
dfl$construct <- factor(dfl$construct, levels = c("FO", "FO accountability"))

plt_fo_a <- ggplot(data = dfl, aes(x = variable, y = value, group = 1)) +
  stat_summary(fun = "mean", geom = "line") +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1) +
  stat_summary(fun = "mean", geom = "point",size = size_dot, color = coral) +
  ambition_theme + xlab("") + ylab("FO accountability") +
  facet_grid(. ~ comp) + coord_cartesian(ylim = c(ymin, ymax))
# plt_fo_a

plt_fo_a_spag <- ggplot(data = dfl, aes(x = variable, y = value, group = 1)) +
  geom_point(size = .5, color = black40) +
  geom_line(aes(group = participant), color = black40, linewidth = .5) +
  stat_summary(fun = "mean", geom = "line") +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1) +
  stat_summary(fun = "mean", geom = "point",size = size_dot, color = coral) +
  ambition_theme + xlab("") + ylab("FO accountability") +
  facet_grid(. ~ comp) #+ coord_cartesian(ylim = c(ymin, ymax))
# plt_fo_a_spag

# --- create facets for FO social awareness only ---

dfl <- rbind(dfl_fo_s, dfl_fo_sw)
dfl$construct <- factor(dfl$construct, levels = c("FO", "FO social awareness"))

plt_fo_s <- ggplot(data = dfl, aes(x = variable, y = value, group = 1)) +
  stat_summary(fun = "mean", geom = "line") +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1) +
  stat_summary(fun = "mean", geom = "point",size = size_dot, color = coral) +
  ambition_theme + xlab("") + ylab("FO social awareness") +
  facet_grid(. ~ comp) + coord_cartesian(ylim = c(ymin, ymax))
# plt_fo_s

plt_fo_s_spag <- ggplot(data = dfl, aes(x = variable, y = value, group = 1)) +
  geom_point(size = .5, color = black40) +
  geom_line(aes(group = participant), color = black40, linewidth = .5) +
  stat_summary(fun = "mean", geom = "line") +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1) +
  stat_summary(fun = "mean", geom = "point",size = size_dot, color = coral) +
  ambition_theme + xlab("") + ylab("FO social awareness") +
  facet_grid(. ~ comp) #+ coord_cartesian(ylim = c(ymin, ymax))
# plt_fo_s_spag


# --- create facets for FO utility only ---

dfl <- rbind(dfl_fo_u, dfl_fo_uw)
dfl$construct <- factor(dfl$construct, levels = c("FO", "FO utility"))

plt_fo_u <- ggplot(data = dfl, aes(x = variable, y = value, group = 1)) +
  stat_summary(fun = "mean", geom = "line") +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1) +
  stat_summary(fun = "mean", geom = "point",size = size_dot, color = coral) +
  ambition_theme + xlab("Survey") + ylab("FO utility") +
  facet_grid(. ~ comp) + coord_cartesian(ylim = c(ymin, ymax))
# plt_fo_u

plt_fo_u_spag <- ggplot(data = dfl, aes(x = variable, y = value, group = 1)) +
  geom_point(size = .5, color = black40) +
  geom_line(aes(group = participant), color = black40, linewidth = .5) +
  stat_summary(fun = "mean", geom = "line") +
  stat_summary(fun.data = "mean_cl_normal", geom = "errorbar", width = .1) +
  stat_summary(fun = "mean", geom = "point",size = size_dot, color = coral) +
  ambition_theme + xlab("Survey") + ylab("FO utility") +
  facet_grid(. ~ comp) #+ coord_cartesian(ylim = c(ymin, ymax))
# plt_fo_u_spag


## --- Combine to create Figure S1 ---

ggpubr::ggarrange(
  plt_fo_a, plt_fo_s, plt_fo_u, nrow = 3, align = "hv")
ggsave(filename = file.path(cd, "FigureS1.jpg"), 
       units = "cm", width = 16, height = 18)
```

```{r, include=F}
ggpubr::ggarrange(plt_fo_spag,
                  plt_fo_u_spag, 
                  plt_fo_a_spag, 
                  plt_fo_s_spag, 
                  plt_fo_e_spag,
                  nrow = 5, align = "hv")
ggsave(filename = file.path(cd, "FigureS1_v2.jpg"), 
       units = "cm", width = 21, height = 30)

```

### Exploratory analysis using time intervall between surveys as covariate

```{r, echo = F, results='asis'}
timings <- read.csv("C:/Users/stefanie.meliss/OneDrive - Ambition Institute/research_projects/Ark Feedback Orientation and Sims/Data/Follow up questionnaire/Survey timings/timings_SM.csv")

df <- merge(df, timings, by = "participant")

psych::describe(df$survey_diff) %>% 
  kbl(caption = "Descriptives of time interval between surveys (in days)") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

hist(df$survey_diff, main = "Time interval between surveys (in days)")

vars <- c("FO",
          "FO utility",
          "FO accountability",
          "FO social awareness",
          "FO self-efficacy")

# determine variable names: summed scores
vars_1 <- vars_sum_1
vars_2 <- vars_sum_2

# loop over vraibles #

for (i in 1:length(vars)) {
  
  v1 <- vars_1[i]
  v2 <- vars_2[i]
  
  time_diff <- "survey_diff"
  
  # run reg
  m1 <- lm(scale(get(v2)) ~ scale(get(time_diff)) * scale(get(v1)),
           data = df)
  # sjPlot::tab_model(m1, show.se = T, show.stat = T, show.ci = F,pred.labels = c("Intercept", cov, FOS[i]))
  
  # get beta coefs
  tmp <- summary(m1)
  coef <- as.data.frame(tmp$coefficients)
  coef[, 4] <- ifelse(coef[, 4] < 0.001, "<.001", weights::rd(coef[, 4], 3))
  coef[,-4] <- round(coef[, -4], 2)
  coef$Predictors <- c("(Intercept)", "Time interval", paste(vars[i], " - Survey 1"), paste0("Time interval x ",vars[i] ))
  row.names(coef) <- NULL
  coef$R2 <- ""
  coef$R2[1] <- weights::rd(tmp$r.squared, 2)
  
  
  if (i == 1) {
    coef_sum <- coef
  } else {
    coef_sum <- rbind(coef_sum, coef)
  }
  
}

coef_sum <- coef_sum %>%
  select(Predictors, everything())

kbl(coef_sum, caption = "Weighted scores") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  pack_rows(paste0(vars[1], " - Survey 2"), 1, 4) %>%
  pack_rows(paste0(vars[2], " - Survey 2"), 5, 8) %>%
  pack_rows(paste0(vars[3], " - Survey 2"), 9, 12) %>%
  pack_rows(paste0(vars[4], " - Survey 2"), 13, 16) %>%
  pack_rows(paste0(vars[5], " - Survey 2"), 17, 20)

# determine variable names: weighted scores
vars_1 <- vars_wtd_1
vars_2 <- vars_wtd_2

for (i in 1:length(vars)) {
  
  v1 <- vars_1[i]
  v2 <- vars_2[i]
  
  time_diff <- "survey_diff"
  
  # run reg
  m1 <- lm(scale(get(v2)) ~ scale(get(time_diff)) * scale(get(v1)),
           data = df)
  # sjPlot::tab_model(m1, show.se = T, show.stat = T, show.ci = F,pred.labels = c("Intercept", cov, FOS[i]))
  
  # get beta coefs
  tmp <- summary(m1)
  coef <- as.data.frame(tmp$coefficients)
  coef[, 4] <- ifelse(coef[, 4] < 0.001, "<.001", weights::rd(coef[, 4], 3))
  coef[,-4] <- round(coef[, -4], 2)
  coef$Predictors <- c("(Intercept)", "Time interval", paste(vars[i], " - Survey 1"), paste0("Time interval x ",vars[i] ))
  row.names(coef) <- NULL
  coef$R2 <- ""
  coef$R2[1] <- weights::rd(tmp$r.squared, 2)
  
  
  if (i == 1) {
    coef_wtd <- coef
  } else {
    coef_wtd <- rbind(coef_wtd, coef)
  }
  
}

coef_wtd <- coef_wtd %>%
  select(Predictors, everything())

kbl(coef_wtd, caption = "Weighted scores") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  pack_rows(paste0(vars[1], " - Survey 2"), 1, 4) %>%
  pack_rows(paste0(vars[2], " - Survey 2"), 5, 8) %>%
  pack_rows(paste0(vars[3], " - Survey 2"), 9, 12) %>%
  pack_rows(paste0(vars[4], " - Survey 2"), 13, 16) %>%
  pack_rows(paste0(vars[5], " - Survey 2"), 17, 20)


# --- create output for export ---#

coef_sum$Estimate <- paste0(coef_sum$Estimate, " (", coef_sum$`Std. Error`,")")
coef_sum$`Std. Error` <- NULL
coef_wtd$Estimate <- paste0(coef_wtd$Estimate, " (", coef_wtd$`Std. Error`,")")
coef_wtd$`Std. Error` <- NULL

coefs <- merge(coef_sum, coef_wtd, by = 0)
coefs <- coefs[order(as.numeric(coefs$Row.names)), ]
coefs$Row.names <- NULL
coefs$Predictors <- coefs$Predictors.x
coefs$Predictors.x <- NULL
coefs$Predictors.y <- NULL


coefs <- coefs %>%
  select(Predictors, everything())

# create headers
header <- coefs[1, ]
header[1, 2:ncol(header)] <- ""

# rbind header with data
header[, 1] <- vars[1]
out <- rbind(header, coefs[1:4, ])
header[, 1] <- vars[2]
out <- rbind(out, header, coefs[5:8, ])
header[, 1] <- vars[3]
out <- rbind(out, header, coefs[9:12, ])
header[, 1] <- vars[4]
out <- rbind(out, header, coefs[13:16, ])
header[, 1] <- vars[5]
out <- rbind(out, header, coefs[17:20, ])

names(out) <- c("", "beta (SE)", "t", "p", "R2", "beta (SE)", "t", "p", "R2")

# save file
write.csv(out,
          file = file.path(cd, "H2_exp.csv"),
          row.names = F)



```



```{r, echo = F, results='asis'}

# determine variable names: summed scores
vars_1 <- vars_sum_1
vars_2 <- vars_sum_2

# loop over vraibles #

for (i in 1:length(vars)) {
  
  v1 <- vars_1[i]
  v2 <- vars_2[i]
  df$diff <- df[, v2] - df[, v1]
  
  
  # run reg
  m1 <- lm(diff ~ scale(survey_diff),
           data = df)
  # sjPlot::tab_model(m1, show.se = T, show.stat = T, show.ci = F,pred.labels = c("Intercept", cov, FOS[i]))
  
  # get beta coefs
  tmp <- summary(m1)
  coef <- as.data.frame(tmp$coefficients)
  coef[, 4] <- ifelse(coef[, 4] < 0.001, "<.001", weights::rd(coef[, 4], 3))
  coef[,-4] <- round(coef[, -4], 2)
  coef$Predictors <- c("(Intercept)", "Time interval")
  row.names(coef) <- NULL
  coef$R2 <- ""
  coef$R2[1] <- weights::rd(tmp$r.squared, 2)
  
  
  if (i == 1) {
    coef_sum <- coef
  } else {
    coef_sum <- rbind(coef_sum, coef)
  }
  
}

coef_sum <- coef_sum %>%
  select(Predictors, everything())

kbl(coef_sum, caption = "Weighted scores") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  pack_rows(paste0(vars[1], " - Improvement"), 1, 2) %>%
  pack_rows(paste0(vars[2], " - Improvement"), 3, 4) %>%
  pack_rows(paste0(vars[3], " - Improvement"), 5, 6) %>%
  pack_rows(paste0(vars[4], " - Improvement"), 7, 8) %>%
  pack_rows(paste0(vars[5], " - Improvement"), 9, 10)

# determine variable names: weighted scores
vars_1 <- vars_wtd_1
vars_2 <- vars_wtd_2

for (i in 1:length(vars)) {
  
  v1 <- vars_1[i]
  v2 <- vars_2[i]
  df$diff <- df[, v2] - df[, v1]
  
  # run reg
  m1 <- lm(diff ~ scale(survey_diff),
           data = df)
  # sjPlot::tab_model(m1, show.se = T, show.stat = T, show.ci = F,pred.labels = c("Intercept", cov, FOS[i]))
  
  # get beta coefs
  tmp <- summary(m1)
  coef <- as.data.frame(tmp$coefficients)
  coef[, 4] <- ifelse(coef[, 4] < 0.001, "<.001", weights::rd(coef[, 4], 3))
  coef[,-4] <- round(coef[, -4], 2)
  coef$Predictors <- c("(Intercept)", "Time interval")
  row.names(coef) <- NULL
  coef$R2 <- ""
  coef$R2[1] <- weights::rd(tmp$r.squared, 2)
  
  
  if (i == 1) {
    coef_wtd <- coef
  } else {
    coef_wtd <- rbind(coef_wtd, coef)
  }
  
}

coef_wtd <- coef_wtd %>%
  select(Predictors, everything())

kbl(coef_wtd, caption = "Weighted scores") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  pack_rows(paste0(vars[1], " - Improvement"), 1, 2) %>%
  pack_rows(paste0(vars[2], " - Improvement"), 3, 4) %>%
  pack_rows(paste0(vars[3], " - Improvement"), 5, 6) %>%
  pack_rows(paste0(vars[4], " - Improvement"), 7, 8) %>%
  pack_rows(paste0(vars[5], " - Improvement"), 9, 10)


# --- create output for export ---#

coef_sum$Estimate <- paste0(coef_sum$Estimate, " (", coef_sum$`Std. Error`,")")
coef_sum$`Std. Error` <- NULL
coef_wtd$Estimate <- paste0(coef_wtd$Estimate, " (", coef_wtd$`Std. Error`,")")
coef_wtd$`Std. Error` <- NULL

coefs <- merge(coef_sum, coef_wtd, by = 0)
coefs <- coefs[order(as.numeric(coefs$Row.names)), ]
coefs$Row.names <- NULL
coefs$Predictors <- coefs$Predictors.x
coefs$Predictors.x <- NULL
coefs$Predictors.y <- NULL


coefs <- coefs %>%
  select(Predictors, everything())

# create headers
header <- coefs[1, ]
header[1, 2:ncol(header)] <- ""

# rbind header with data
header[, 1] <- vars[1]
out <- rbind(header, coefs[1:2, ])
header[, 1] <- vars[2]
out <- rbind(out, header, coefs[3:4, ])
header[, 1] <- vars[3]
out <- rbind(out, header, coefs[5:6, ])
header[, 1] <- vars[4]
out <- rbind(out, header, coefs[7:8, ])
header[, 1] <- vars[5]
out <- rbind(out, header, coefs[9:10, ])

names(out) <- c("", "beta (SE)", "t", "p", "R2", "beta (SE)", "t", "p", "R2")

# save file
write.csv(out,
          file = file.path(cd, "H2_exp_v2.csv"),
          row.names = F)



```



### Above median time interval between surveys only

```{r, echo = F, results='asis'}

# create DF for export
out <- data.frame(
  variable = character(5),
  survey1 = character(5),
  survey2 = character(5),
  diff = character(5),
  ttest = character(5)
)

# only select data from participants that had above median split values for time interval
df_tmp <- df[df$survey_diff > median(df$survey_diff),]



# determine variable names: summed scores
vars_1 <- vars_sum_1
vars_2 <- vars_sum_2

# loop over vraibles #

for (i in 1:length(vars)) {
  
  v1 <- vars_1[i]
  v2 <- vars_2[i]
  
  # run paired t-test
  ttest <- t.test(y = df_tmp[, v1],
                  x = df_tmp[, v2],
                  paired = T)
  
  # get survey 1 descriptives
  survey1 <- round(psych::describe(df_tmp[, v1]), 2)
  # get survey 2 descriptives
  survey2 <- round(psych::describe(df_tmp[, v2]), 2)
  # get diff descriptives
  df_tmp$diff <- df_tmp[, v2] - df_tmp[, v1]
  diff <- round(psych::describe(df_tmp[, "diff"]), 2)
  
  # fill table #
  out[i, "variable"] <- vars[i]
  out[i, "survey1"] <- paste0(survey1$mean, " (", survey1$sd, ") [", survey1$min, "; ", survey1$max, "]")
  out[i, "survey2"] <- paste0(survey2$mean, " (", survey2$sd, ") [", survey2$min, "; ", survey2$max, "]")
  out[i, "diff"] <- paste0(diff$mean, " (", diff$sd, ") [", diff$min, "; ", diff$max, "]")
  out[i, "ttest"] <- paste0("t(", ttest$parameter, ") = ", round(ttest$statistic, 2), ", p = ", ifelse(ttest$p.value < 0.001, "<.001", weights::rd(ttest$p.value, 3)), ", Cohen's d = ", round(lsr::cohensD(y = df_tmp[, v1], x = df_tmp[, v2], method = "paired"), 2))
  
}

summed <- out

kbl(summed, caption = "Summed scores") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))


# create DF for export
out <- data.frame(
  variable = character(5),
  survey1 = character(5),
  survey2 = character(5),
  diff = character(5),
  ttest = character(5)
)

# determine variable names: weighted scores
vars_1 <- vars_wtd_1
vars_2 <- vars_wtd_2

# loop over vraibles #

for (i in 1:length(vars)) {
  
  v1 <- vars_1[i]
  v2 <- vars_2[i]
  
  # run paired t-test
  ttest <- t.test(y = df_tmp[, v1],
                  x = df_tmp[, v2],
                  paired = T)
  
  # get survey 1 descriptives
  survey1 <- round(psych::describe(df_tmp[, v1]), 2)
  # get survey 2 descriptives
  survey2 <- round(psych::describe(df_tmp[, v2]), 2)
  # get diff descriptives
  df_tmp$diff <- df_tmp[, v2] - df_tmp[, v1]
  diff <- round(psych::describe(df_tmp[, "diff"]), 2)
  
  # fill table #
  out[i, "variable"] <- vars[i]
  out[i, "survey1"] <- paste0(survey1$mean, " (", survey1$sd, ") [", survey1$min, "; ", survey1$max, "]")
  out[i, "survey2"] <- paste0(survey2$mean, " (", survey2$sd, ") [", survey2$min, "; ", survey2$max, "]")
  out[i, "diff"] <- paste0(diff$mean, " (", diff$sd, ") [", diff$min, "; ", diff$max, "]")
  out[i, "ttest"] <- paste0("t(", ttest$parameter, ") = ", round(ttest$statistic, 2), ", p = ", ifelse(ttest$p.value < 0.001, "<.001", weights::rd(ttest$p.value, 3)), ", Cohen's d = ", round(lsr::cohensD(y = df_tmp[, v1], x = df_tmp[, v2], method = "paired"), 2))
  
}


weighted <- out

kbl(weighted, caption = "Weighted scores") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))


# combine both
out <- merge(summed, weighted, by = "variable")
names(out) <- c("","Survey 1", "Survey 2", "Improvement", "Paired t-test")

write.csv(out, file = file.path(cd, "H2_twosided_mediansplit.csv"), row.names = F)

```


